[build-system]
requires = ["setuptools >= 64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rgevolve"
authors = [
    {name = "Aleks Smolkovič", email = "aleks.smolkovic@ijs.si"},
    {name = "Peter Stangl", email = "peter.stangl@cern.ch"},
]
description = "Package providing Renormalization Group Evolution Matrices."
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "numpy",
    "appdirs",
    "h5py",
]
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["src/"]
include = ["rgevolve.tools", "rgevolve.matching"]

[tool.setuptools.dynamic]
version = {attr = "rgevolve.tools._version.__version__"}

[tool.setuptools.package-data]
"rgevolve.matching" = ["data.h5"]
